/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* DependencyUpdate describes an dependency update message from the commit log
*/
export interface DependencyUpdate {
    'component': string;
    'fromReleaseHTMLURL': string;
    'fromReleaseName': string;
    'fromVersion': string;
    'host': string;
    'owner': string;
    'repo': string;
    'toReleaseHTMLURL': string;
    'toReleaseName': string;
    'toVersion': string;
    'URL': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "component",
            "baseName": "Component",
            "type": "string"
        },
        {
            "name": "fromReleaseHTMLURL",
            "baseName": "FromReleaseHTMLURL",
            "type": "string"
        },
        {
            "name": "fromReleaseName",
            "baseName": "FromReleaseName",
            "type": "string"
        },
        {
            "name": "fromVersion",
            "baseName": "FromVersion",
            "type": "string"
        },
        {
            "name": "host",
            "baseName": "Host",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "Owner",
            "type": "string"
        },
        {
            "name": "repo",
            "baseName": "Repo",
            "type": "string"
        },
        {
            "name": "toReleaseHTMLURL",
            "baseName": "ToReleaseHTMLURL",
            "type": "string"
        },
        {
            "name": "toReleaseName",
            "baseName": "ToReleaseName",
            "type": "string"
        },
        {
            "name": "toVersion",
            "baseName": "ToVersion",
            "type": "string"
        },
        {
            "name": "URL",
            "baseName": "URL",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DependencyUpdate.attributeTypeMap;
    }
}

