/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobBase } from './jobBase';
import { ReplaceableSliceOfStrings } from './replaceableSliceOfStrings';

/**
* Periodic defines a job to be run periodically
*/
export interface Periodic {
    'jobBase'?: JobBase;
    /**
    * Cron representation of job trigger time
    */
    'cron': string;
    /**
    * Interval to wait between two runs of the job.
    */
    'interval': string;
    'tags'?: ReplaceableSliceOfStrings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jobBase",
            "baseName": "JobBase",
            "type": "JobBase"
        },
        {
            "name": "cron",
            "baseName": "cron",
            "type": "string"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "ReplaceableSliceOfStrings"
        }    ];

    static getAttributeTypeMap() {
        return Periodic.attributeTypeMap;
    }
}

