/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Periodic } from './periodic';

/**
* Periodics is a list of jobs to be run periodically
*/
export interface Periodics {
    /**
    * Items are the post submit configurations
    */
    'entries'?: Array<Periodic>;
    /**
    * Replace the existing entries
    */
    'replace'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<Periodic>"
        },
        {
            "name": "replace",
            "baseName": "replace",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Periodics.attributeTypeMap;
    }
}

