/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Approve } from './approve';
import { Attachment } from './attachment';
import { ConfigUpdater } from './configUpdater';
import { GlobalProtectionPolicy } from './globalProtectionPolicy';
import { Lgtm } from './lgtm';
import { Merger } from './merger';
import { Periodics } from './periodics';
import { Postsubmits } from './postsubmits';
import { Presubmits } from './presubmits';
import { ReplaceableSliceOfExternalPlugins } from './replaceableSliceOfExternalPlugins';
import { ReplaceableSliceOfStrings } from './replaceableSliceOfStrings';
import { SchedulerAgent } from './schedulerAgent';
import { Trigger } from './trigger';
import { Welcome } from './welcome';

/**
* SchedulerSpec defines the pipeline scheduler (e.g. Prow) configuration
*/
export interface SchedulerSpec {
    'approve'?: Approve;
    'attachments'?: Array<Attachment>;
    'configUpdater'?: ConfigUpdater;
    'externalPlugins'?: ReplaceableSliceOfExternalPlugins;
    'lgtm'?: Lgtm;
    'merger'?: Merger;
    'periodics'?: Periodics;
    'plugins'?: ReplaceableSliceOfStrings;
    'policy'?: GlobalProtectionPolicy;
    'postsubmits'?: Postsubmits;
    'presubmits'?: Presubmits;
    'schedulerAgent'?: SchedulerAgent;
    'trigger'?: Trigger;
    'welcome'?: Array<Welcome>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "approve",
            "baseName": "approve",
            "type": "Approve"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<Attachment>"
        },
        {
            "name": "configUpdater",
            "baseName": "configUpdater",
            "type": "ConfigUpdater"
        },
        {
            "name": "externalPlugins",
            "baseName": "externalPlugins",
            "type": "ReplaceableSliceOfExternalPlugins"
        },
        {
            "name": "lgtm",
            "baseName": "lgtm",
            "type": "Lgtm"
        },
        {
            "name": "merger",
            "baseName": "merger",
            "type": "Merger"
        },
        {
            "name": "periodics",
            "baseName": "periodics",
            "type": "Periodics"
        },
        {
            "name": "plugins",
            "baseName": "plugins",
            "type": "ReplaceableSliceOfStrings"
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "GlobalProtectionPolicy"
        },
        {
            "name": "postsubmits",
            "baseName": "postsubmits",
            "type": "Postsubmits"
        },
        {
            "name": "presubmits",
            "baseName": "presubmits",
            "type": "Presubmits"
        },
        {
            "name": "schedulerAgent",
            "baseName": "schedulerAgent",
            "type": "SchedulerAgent"
        },
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "Trigger"
        },
        {
            "name": "welcome",
            "baseName": "welcome",
            "type": "Array<Welcome>"
        }    ];

    static getAttributeTypeMap() {
        return SchedulerSpec.attributeTypeMap;
    }
}

