/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceReference } from './resourceReference';

/**
* SourceRepositorySpec provides details of the metadata for an App
*/
export interface SourceRepositorySpec {
    'description'?: string;
    /**
    * HTTPCloneURL is the git URL to clone this repository using HTTP/HTTPS
    */
    'httpCloneURL'?: string;
    'org'?: string;
    /**
    * Provider stores the URL of the git provider such as https://github.com
    */
    'provider'?: string;
    /**
    * ProviderKind is the kind of provider (github / bitbucketcloud / bitbucketserver etc)
    */
    'providerKind'?: string;
    /**
    * ProviderName is a logical name for the provider without any URL scheme which can be used in a label selector
    */
    'providerName'?: string;
    'repo'?: string;
    'scheduler'?: ResourceReference;
    /**
    * SSHCloneURL is the git URL to clone this repository using SSH
    */
    'sshCloneURL'?: string;
    /**
    * URL is the web URL of the project page
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "httpCloneURL",
            "baseName": "httpCloneURL",
            "type": "string"
        },
        {
            "name": "org",
            "baseName": "org",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "providerKind",
            "baseName": "providerKind",
            "type": "string"
        },
        {
            "name": "providerName",
            "baseName": "providerName",
            "type": "string"
        },
        {
            "name": "repo",
            "baseName": "repo",
            "type": "string"
        },
        {
            "name": "scheduler",
            "baseName": "scheduler",
            "type": "ResourceReference"
        },
        {
            "name": "sshCloneURL",
            "baseName": "sshCloneURL",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SourceRepositorySpec.attributeTypeMap;
    }
}

