/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Welcome welcome plugin config
*/
export interface Welcome {
    'messageTemplate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messageTemplate",
            "baseName": "message_template",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Welcome.attributeTypeMap;
    }
}

